import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';

if (process.argv.includes('--help')) { console.log('node scripts/generate.mjs [--check]: build self-contained skill helpers and pack manifests; check never writes.'); process.exit(0); }
const root = fileURLToPath(new URL('../', import.meta.url));
const load = file => readFileSync(join(root, file), 'utf8');
const pack = JSON.parse(load('pack.json'));
const check = process.argv.includes('--check');
const outputs = new Map();
const json = value => `${JSON.stringify(value, null, 2)}\n`;
const skills = readdirSync(join(root, 'skills')).sort();
const descriptions = [];
for (const skill of skills) {
  const file = `skills/${skill}/SKILL.md`;
  const text = load(file), front = /^---\n([\s\S]+?)\n---\n/.exec(text);
  if (!front || parse(front[1]).name !== skill) throw new Error(`Invalid skill: ${skill}`);
  descriptions.push([skill, parse(front[1]).description.split('. ')[0].trim().replace(/\.$/, '') + '.']);
  outputs.set(file, text.replace(/^  version: .*$/m, `  version: "${pack.version}"`));
  for (const module of ['bookmarks', 'repository', 'cli']) outputs.set(`skills/${skill}/scripts/lib/${module}.mjs`, load(`src/${module}.mjs`));
  outputs.set(`skills/${skill}/scripts/evergreen.mjs`, "#!/usr/bin/env node\n// Generated by scripts/generate.mjs; edit src/, not this bundle.\nimport { main } from './lib/cli.mjs';\nmain();\n");
}
// Shared instructions are included in both installations, generated from one canonical source.
outputs.set('skills/evergreen-context/references/repository.md', load('skills/evergreen-bookmarks/references/repository.md'));
const common = Object.fromEntries(['name', 'version', 'description', 'author', 'repository', 'license', 'keywords'].map(key => [key, pack[key]]));
outputs.set('.claude-plugin/plugin.json', json(common));
outputs.set('plugin.json', json({ $schema: 'https://agent-plugins.org/schemas/1.0.0/plugin.schema.json', ...common }));
outputs.set('.claude-plugin/marketplace.json', json({ ...pack.marketplace, plugins: [{ name: pack.name, source: './', description: pack.description, version: pack.version }] }));
outputs.set('package.json', json({ ...JSON.parse(load('package.json')), version: pack.version }));
const start = '<!-- generated:skills:start (build-manifests.mjs; do not edit) -->';
const stop = '<!-- generated:skills:end -->';
const readme = load('README.md');
if (!readme.includes(start) || !readme.includes(stop)) throw new Error('README generated markers missing.');
const table = `${start}\n\n| skill | what it does |\n| -- | -- |\n${descriptions.map(([name, desc]) => `| [\`${name}\`](skills/${name}/SKILL.md) | ${desc} |`).join('\n')}\n\n${stop}`;
outputs.set('README.md', readme.slice(0, readme.indexOf(start)) + table + readme.slice(readme.indexOf(stop) + stop.length));
const stale = [];
for (const [file, content] of outputs) {
  const path = join(root, file);
  if (existsSync(path) && readFileSync(path, 'utf8') === content) continue;
  if (check) stale.push(file);
  else { mkdirSync(dirname(path), { recursive: true }); writeFileSync(path, content); }
}
if (stale.length) throw new Error(`Generated files are stale: ${stale.join(', ')}. Run npm run generate.`);
console.log(`${outputs.size} generated files ${check ? 'checked' : 'built'}.`);
